version: "3"

services:

  finbourne-notifications-sdk-csharp-build:
    build: .
    container_name: finbourne-notifications-sdk-csharp-build
    image: finbourne/finbourne-notifications-sdk-csharp-build
    environment:
      - FBN_TOKEN_URL
      - FBN_USERNAME
      - FBN_PASSWORD
      - FBN_CLIENT_ID
      - FBN_CLIENT_SECRET
      - FBN_NOTIFICATOPMS_API_URL
      - FBN_APP_NAME
    volumes:
      - .:/usr/src